osx_image: xcode6.4

language: objective-c

#before_install:
#- export LANG=en_US.UTF-8
#- brew update
#- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xcodebuild clean build test -project DKImagePickerControllerDemo.xcodeproj -scheme DKImagePickerControllerDemo -destination 'platform=iOS Simulator,name=iPhone 5s'
